### ISSUE TITLE
Multiple configurable_variations attributes not supported

### ISSUE THREAD

**Issue by Morgy93** [techdivision/import-product-variant#21]
If you provide multiple attributes for `configurable_variations` only the first one is imported.
For example: `sku=1,color=red,size=1|sku=2,color=blue,size=2`
Only color is added to the configurable product as configurable attribute variation.

**Comment by wagnert** [comment]
@Morgy93 I've released version [3.1.0-beta14](https://github.com/techdivision/import-cli-simple/releases/tag/3.1.0-beta14) if you're on Magento 2.3.x. If you're on Magento 2.2.x please use [2.2.0-beta12](https://github.com/techdivision/import-cli-simple/releases/tag/2.2.0-beta12). Keep me updated if everything works as expected. If not, feel free to re-open the issue.
