### ISSUE TITLE
Add an option to reset catalog_product_super_link entries for imported products during add_update

### ISSUE THREAD

**Issue by amenk** [techdivision/import-product-variant#22]
When importing with add_update, it should be possible to reset the full configurable data / delete data which is not specified in the variations column any more.

This seems to be already possible with replace mode, but it would recreate each product which is not good most of the time.

**Comment by amenk** [comment]
@wagnert What is the status of this? There are plenty of merge requests merged, is this already available in dev ?

**Comment by wagnert** [comment]
Good morning @amenk as it looks like [here](https://github.com/techdivision/import-product-variant/blob/master/src/Observers/CleanUpVariantProductRelationObserver.php#L93) this functionality has already been added but not been documented :-(

**Comment by amenk** [comment]
Seems to work, thank you :-)
We just needed to add

                                        "clean-up-variants": true,

to our import operation.
